minimumReleaseAgeExcludePrune: true
trustPolicy: off
shellEmulator: true

configDependencies:
  '@pnpm/plugin-trusted-deps': latest

allowBuilds:
  '@vscode/vsce-sign': true
  esbuild: true
  keytar: true
